[workspace]

members = [
    "base64_bench",
    "base64_jdk",
    "base64_manual_bench",
    "crypto2_base64",
]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
